laba12/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :users
  resources :sessions, only: %i[new create destroy]

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  get 'number/input'
  get 'number/view'

  root 'sessions#new'

end

laba12/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

laba12/app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, presence: true, uniqueness: true
end

laba12/app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  helper_method :current_user
  before_action :require_auth, except: %i[new edit destroy create show index]

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else
      @current_user = nil
    end
  end

  def require_auth
    current_user
    redirect_to login_path unless @current_user
  end
end

laba12/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

laba12/app/controllers/number_controller.rb
# frozen_string_literal: true

# controller for calculate result
class NumberController < ApplicationController

  def input; end

  def dividers_sum_with_number(number)
    [number, 1.upto(number - 1).select { |v| (number % v).zero? }.sum]
  end

  # @param [Object] num
  def friends_number(num)
    mas = 1.upto(num).map { |i| dividers_sum_with_number(i) }
    mas.permutation(2).each_with_object([]) do |v, result|
      next unless (v[0][0] == v[1][1]) && (v[0][1] == v[1][0]) && (v[0][0] != v[1][0])

      pair = [v[0][0], v[1][0]]
      result << pair unless result.include?([v[1][0], v[0][0]])
    end
  end

  # @return [Integer, Enumerator]
  def view
    n = params[:number].to_i
    @result = if n.zero?
                -1 # incorrect input
              else
                res = friends_number(n)
                if res.length.zero?
                  0 # no friends numbers
                else
                  res # correct data: successful complete
                end
              end
  end


end

laba12/app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by_email(params[:email])
    if user&.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to number_input_url
    else
      flash.now[:alert] = 'Email or password is invalid'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'Logged out!'
  end
end

laba12/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
        #format.html { redirect_to number_input_path }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end


end

laba12/app/helpers/application_helper.rb
module ApplicationHelper
end

laba12/app/helpers/home_helper.rb
module HomeHelper
end

laba12/app/helpers/number_helper.rb
module NumberHelper
end

laba12/app/helpers/sessions_helper.rb
module SessionsHelper
end

laba12/app/helpers/users_helper.rb
module UsersHelper
end

laba12/app/views/home/index.html.erb
<p id=”notice”><%= notice %></p>
<h1>Example</h1>
<p>Lorem ipsum …</p>

laba12/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Laba12</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

laba12/app/views/number/input.html.erb
<h1>Вычисление дружественных чисел от 1 до n</h1>
<p>Два числа называются взаимно дружественными, если каждое из них
  равно сумме всех делителей другого, кроме самого этого числа.</p>
<%= form_tag("/number/view", :method => "get") do %>
  <%= label_tag("Введите n") %>
  <%= text_field_tag(:number) %>  <br/>
  <br/>
  <%= submit_tag("Рассчитать") %>
<% end %>
<%= link_to "Log out", logout_path %>

laba12/app/views/number/view.html.erb
<h1>Результат</h1>
<p>Таблица взаимно дружественных чисел</p>
<% if @result == -1 %>
  <P>Некорректные данные</P>
<% elsif @result == 0 %>
  <P>Взаимно дружественных чисел нет</P>
<% else %>
  <table>
    <% @result.each do |v| %>
      <tr>
        <td><%= v[0] %></td>
        <td><%= v[1] %></td>
      </tr>
    <% end %>
  </table>
<% end %>
<br><br>
<%= link_to "Повторить вычисления", :number_input %>
<%= link_to "Log out", logout_path %>

laba12/app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
<%= link_to "Log out", logout_path %>

laba12/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %>

<!-- <%#= link_to 'Back', users_path %>-->

laba12/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Main</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>


  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if current_user %>
  Logged in as <%= current_user.email %>.
  <%= link_to 'Log Out', logout_path %>
<% else %>
  <%= link_to 'Sign Up', signup_path %> or
  <%= link_to 'Log In', login_path %>
<% end %><p id=”notice”><%= notice %></p>


<%= link_to 'New User', new_user_path %>

laba12/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

laba12/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'All users', users_path %>
<br>
<%= link_to 'Log in', login_path %>